1. Create a Function that can take in a   square  matrix and display the boundary of the matrix in a circular manner  without any repeating elements 

In [3]:
import numpy as np
a = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

In [4]:
b = np.array(a)

In [5]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# first_and_third_column = an_array[:, [0, 2]]
first_third = b[:, [0, 2]]

In [7]:
first_third

array([[1, 3],
       [4, 6],
       [7, 9]])

In [8]:
first_third[:, [0]]

array([[1],
       [4],
       [7]])

In [9]:
b[[0], :]

array([[1, 2, 3]])

In [10]:
b[:, [-1]]

array([[3],
       [6],
       [9]])

In [11]:
import pandas as pd

In [12]:
s1 = pd.Series({'A':330.0, 'C':160.0})
s2 = pd.Series({'B':345.0, 'B':200.0, 'C':30.0})

In [13]:
s1.combine(s2, min)

A    330.0
B      NaN
C     30.0
dtype: float64

In [15]:
s1.combine(s2, lambda x1, x2: x1*2 if x1*2 > x2*2 else x2*2)

A      NaN
B    400.0
C    320.0
dtype: float64